---
# tasks file for rotorhazard

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ rh_dependencies }}"

# - name: Create tmp directory
#   file:
#     path: "{{ tmp_dir }}"
#     state: directory
#     mode: rwx

- name: Add RotorHazard group
  group:
    name: "{{ rh_group }}"
    state: present

- name: Add RotorHazard user
  user:
    name: "{{ rh_user }}"
    comment: "RotorHazard user"
    group: "{{ rh_group }}"
    state: present

- name: Add RotorHazard user to group additional groups
  user:
    name: "{{ rh_user }}"
    groups:
      - dialout
      - i2c
    append: yes

- name: Create directory
  file:
    path: "{{target_dir }}"
    state: directory
    owner: "{{ rh_user }}"
    group: "{{ rh_group }}"

- name: Download RotorHazard source
  become: false
  get_url:
    url: "https://github.com/RotorHazard/RotorHazard/archive/refs/tags/{{ version }}.tar.gz"
    dest: "{{ tmp_dir }}/RotorHazard-{{ version }}.tar.gz"
  register: _download_source
  until: _download_source is succeeded
  retries: 5
  delay: 2
  # delegate_to: localhost
  check_mode: false

- name: Unpack RotorHazard source
  become: false
  unarchive:
    src: "{{ tmp_dir }}/RotorHazard-{{ version }}.tar.gz"
    dest: "{{ tmp_dir }}"
    remote_src: yes
  check_mode: false

- name: Move RotorHazard source
  copy:
    remote_src: true
    src: "{{ tmp_dir }}/RotorHazard-{{ version }}/"
    dest: "{{ target_dir }}/"

- name: Install specified RotorHazard requirements
  pip:
    requirements: "{{ work_dir }}/requirements.txt"

- name: Create RotorHazard config
  copy:
    content: "{{rh_config | to_nice_json}}"
    dest: "{{ work_dir }}/config.json"

- name: Create RotorHazard logs directory
  file:
    path: "{{ logs_dir }}"
    state: directory
    owner: "{{ rh_user }}"
    group: "{{ rh_group }}"

- name: Create systemd unit
  become: true
  template:
    src: "service_systemd.j2"
    dest: "/lib/systemd/system/{{ rh_service_name }}.service"
    force: true
    owner: root
    group: root
    mode: "0644"

- name: Start RotorHazard
  become: true
  systemd:
    name: '{{ rh_service_name }}'
    state: restarted
    enabled: true
    daemon_reload: yes